### ISSUE TITLE
Add BigInteger version of getBytes

### ISSUE THREAD

**Issue by havocp** [lightbend/config#172]
We support huge unit prefixes like yottabytes that can't fit in a long, so either drop that support or add a BigInteger-based accessor.

This is an API addition so would go in a 1.4

**Comment by mpryahin** [comment]
Hello,
I came across this requirement multiple times. And now once again. I need to pass a configuration option containing memory size which doesn't fit 64 bits.  It would be fantastic if we had this feature implemented in TypeSafe Config. 
I propose the enhancement by introducing the following backwards-compatible changes:

1.  `ConfigMemorySize` class. Add a factory method constructing `ConfigMemorySize` class instances taking a `BigInteger` as an argument.
2.  `SimpleConfig` class. Change the `getMemorySize` implementation to create `ConfigMemorySize` class instances passing `BigInteger` as an argument. 
3.  `ConfigMemorySize` class. Introduce a new method `toByteArray` returning a byte array containing the twos-complement representation of this `BigInteger`. 
4.  ConfigMemorySize class. Keep the `toBytes` method for backward compatibility. The implementation tries extracting Long value out of a BigInteger in case it fits 64 bytes. It is exactly how it's implemented in the getBytes method of the `SimpleConfig` class.

I'm ready to create a PR.

**Comment by mpryahin** [comment]
[PR is ready](https://github.com/lightbend/config/pull/663), could you please review it

**Comment by mpryahin** [comment]
> Though it's pretty hard to come up with use-cases for byte counts that don't fit in a long, I guess.

Hi @havocp,
We're using Aerospike in our project which stores keys in RAM and data on disk. We need to limit the maximum amount of RAM which is allowed to be consumed. The maximum RAM value for a single Aerospike Set is defined as a maximum number of unique keys per Set multiplied by 64 bytes each where the maximum number of unique keys is limited by the hash function (RIPEMD-160) which can produce 2^160 unique values.  The value of 64*2^160 bytes doesn't fit in a long.

Could you please have a look at the [PR](https://github.com/lightbend/config/pull/663)?

Thanks a lot in advance!

**Comment by mpryahin** [comment]
hello @havocp 
I just wanted to ask when approximately you are going to merge the approved [PR](https://github.com/lightbend/config/pull/663) into the main branch?
