### ISSUE TITLE
Support for Java < 8

### ISSUE THREAD

**Issue by 2m** [lightbend/config#379]
[There have been requests](https://gitter.im/typesafehub/config?at=56e8f9ee6fde057c26872d3c) for having all of the latest features and bugfixes available for Java < 8.

This issue should be used as a place to coordinate the effort.

One of the approaches would be to keep a branch for `1.2.x` Java 6 releases. This might be okay if only specific features from master are needed on `1.2.x`. But if a more-or-less complete sync with the master is wanted, then this might have too big of a maintenance burden as every change to the master will have to be backported to the said branch.

Another approach would be to have a separate release artifact with a `java6` classifier (some projects seem to [already do this](http://search.maven.org/#search%7Cga%7C1%7Cl%3A%22java6%22)). I think releasing such an artifact might involve removing methods from public library APIs that use Java 8 APIs. Then such an artifact might even be built with Java 8 using `-source 1.6 -target 1.6`, given that the codepath to Java 8 specific APIs is no longer accessible from the user visible API.

I found some more info on this topic [here](https://spring.io/blog/2015/04/03/how-spring-achieves-compatibility-with-java-6-7-and-8).

//cc @tylerjharden @spockz

**Comment by tylerjharden** [comment]
I will do some research and see where to get started on this.

**Comment by spockz** [comment]
@tylerjharden Do you have any updates regarding this?

**Comment by SethTisue** [comment]
in 2019, I really don't think this is worth doing. I'm going to close the ticket (but bigger bigwigs in this repo can override the decision, of course)
