### ISSUE TITLE
Support for more than one comment per node?

### ISSUE THREAD

**Issue by FerusGrim** [lightbend/config#458]
So I'm in love with a configuration wrapper with uses TypeSafe's Config library.

You can find it [here](https://github.com/zml2008/configurate).

The issue is that nodes which contain multiple comments get condensed into a single line.

EG:
```hocon
# What message should be displayed to kicked users?
# {user} : The username. If can't be found, displays "Unknown User".
deny-message = "Sorry {user}, you're not whitelisted! Visit https://forums.mywebsite.com to apply!";
```

Gets turned into:

```hocon
# What message should be displayed to kicked users? {user} : The username. If can't be found, displays "Unknown User".
deny-message="Sorry {user}, you're not whitelisted! Visit https://forums.mywebsite.com to apply!;"
```

I've tried my best to solve this issue by looking at Configurate, but so far as I can tell, it's an issue that's occurring when Configurate calls on TypeSafe to parse the configuration.

The relevant issue is located [here](https://github.com/zml2008/configurate/issues/74).

I know that asking a developer to assist with third-party code is quite literally the bane of a programmer's existence, so maybe I should be a tad more direct.

Is there anything about these two lines:
```java
Config hoconConfig = ConfigFactory.parseReader(reader, parse);
hoconConfig = hoconConfig.resolve();
```
Which would cause multi-line comments which, so far as I can tell, are being properly handled to be reduced to a single line?

**Comment by havocp** [comment]
You are saying Configurate does a load and then a save, which changes the comment?

I didn't think typesafe config combined comment lines like this so maybe that's from some quirk, but in general typesafe config does not preserve formatting through instances of the Config object. There is a syntax tree object ConfigDocument which does preserve formatting but it isn't the main API for reading configuration, more of a raw file parser.

**Comment by FerusGrim** [comment]
I narrowed the issue down to loading.

If I load the configuration file and programatically output the comments, they're combined - no saving involved.

From everything I've been able to tell, the only interactions that Configurate has with comments handles multiple comments correctly.

I'm not sure what your ConfigDocument does. The only reference I can gather to TypeSafe are the two lines posted above.

If you can confirm they shouldn't affect multiple comment lines, then I can go back and keep looking for the issue within Configurate.

**Comment by havocp** [comment]
Neither of the lines you posted renders or saves the config as a string, so it isn't clear to me where/how that happens. If it's via the render() method, that method does not attempt to preserve formatting. I didn't think it combined comment lines but if it does it's "within spec" to do so because preserving formatting isn't the intent of that method.

The class which does preserve formatting is called ConfigDocument.

Have you tried asking the Configurate maintainers about it?

**Comment by FerusGrim** [comment]
I think that I was unclear how Configurate works.

The ultimate goal is to take `Config` and its values and transform them into what Configurate calls a `ConfigurationNode`.

```java
    @Override
    public void loadInternal(CommentedConfigurationNode node, BufferedReader reader) throws IOException {
        Config hoconConfig = ConfigFactory.parseReader(reader, parse);
        hoconConfig = hoconConfig.resolve();
        for (Map.Entry<String, ConfigValue> ent : hoconConfig.root().entrySet()) {
            readConfigValue(ent.getValue(), node.getNode(ent.getKey()));
        }
    }

    private void readConfigValue(ConfigValue value, CommentedConfigurationNode node) {
        if (!value.origin().comments().isEmpty()) {
            node.setComment(CRLF_MATCH.matcher(Joiner.on('\n').join(value.origin().comments())).replaceAll(""));
        }
        switch (value.valueType()) {
            case OBJECT:
                if (((ConfigObject) value).isEmpty()) {
                    node.setValue(ImmutableMap.of());
                } else {
                    for (Map.Entry<String, ConfigValue> ent : ((ConfigObject) value).entrySet()) {
                        readConfigValue(ent.getValue(), node.getNode(ent.getKey()));
                    }
                }
                break;
            case LIST:
                List<ConfigValue> values = (ConfigList) value;
                for (int i = 0; i < values.size(); ++i) {
                    readConfigValue(values.get(i), node.getNode(i));
                }
                break;
            case NULL:
                return;
            default:
                node.setValue(value.unwrapped());
        }
    }
```

That's the entire code that has any relevancy to TypeSafe.

In `loadInternal`, the default `ConfigParseOptions` and a `BufferedReader` of the file are passed to the two lines I posted above (reposted below here for convenience/clarification):

```java
        Config hoconConfig = ConfigFactory.parseReader(reader, parse);
        hoconConfig = hoconConfig.resolve();
```

The _only_ time Configurate touches comments is in the following check in the `readConfigValue` method:

```java
        if (!value.origin().comments().isEmpty()) {
            node.setComment(CRLF_MATCH.matcher(Joiner.on('\n').join(value.origin().comments())).replaceAll(""));
        }
```

I've tested these specific lines on a test program:

```java
public class TestMain {

    public static final Pattern CRLF_MATCH = Pattern.compile("\r\n?");

    public static void main(String[] args){
        final List<String> comments = Lists.newArrayList("This is a comment.", "And this is another.");
        output(comments);
        output(CRLF_MATCH.matcher(Joiner.on('\n').join(comments)).replaceAll(""));
    }

    private static void output(List<String> comments) {
        for (final String comment : comments) {
            System.out.println(comment);
        }

        System.out.println();
    }

    private static void output(String comment) {
        System.out.println(comment);
    }
}
```

This is the output:
```stack
This is a comment.
And this is another.

This is a comment.
And this is another.
```

So far as I can tell, assuming that the comments are separated into a list (which it appears those two calls to TypeSafe is supposed to resolve in, from what I can tell), this shouldn't cause any problems.

What I'm able to understand:
1. Configurate reads the source into a `BufferedReader`
2. Configurate passes the `BufferedReader` and the default `ConfigParseOptions` to TypeSafe
3. Configurate then adds the TypeSafe-generated comments into the node.
4. At some point between 1-3, comments are converged into a single line.

As far as reaching the developer of Configurate, the issue has been left unanswered for almost a month. I've recently tried getting a hold of him on IRC, but he doesn't seem to be online. /shrug

**Comment by ryantheleach** [comment]
@FerusGrim Long story short @havocp is saying that this is a minor issue, as formatting for the *whole configuration* isn't retained across loading and saving. Configurate saves the configs. the only way around this would be to not save the configs out, or use the ConfigDocument. Early design decisions in how Typesafehub/Config work makes it incompatible with our needs of being able to load, edit values only and not structure, and save out the config again without formatting changes.

We can attempt to chase issues one by one like these comments, but in the current 'config' release we can't even maintain ordering of nodes, let alone new lines in comments.

@havocp The main draw to being able to let the application save and edit config files, is to give access to users the ability to edit the configuration, without having file access inside the application.

In addition these changes that prevent round-trip serialization without changing the format, make it incredibly hard to have decent diffs, version management of configurations for something that is changed within the application.

It's literally the **only** thing that prevents me from recommending hocon/config to everyone.

I understand your position that with the inheritance structure that you can not make the guarantee of where modifications might occur, But if the comments were fixed so they survive round tripping, the ordering of nodes were fixed so they survive if the **structure** is unmodified, and that written values had a configurable file that changes would be persisted to, I think that would go a long way to making the configs more usable.

**Comment by havocp** [comment]
There's a plan of record here which is to make ConfigDocument more powerful see #300. I don't think that task is especially more difficult than trying to add a bunch of format-preservation hacks to Config, and it would support many more use-cases than round trip (such as linting, reformatting), and it would preserve 100% of formatting perfectly.

The usual runtime representation of a config really should not keep an entire syntax tree around just in case somebody saves. Syntax tree should be its own API with suitable methods and data structures. Syntax manipulation needs a bunch of distinct APIs.

ConfigDocument does already support round trip with a couple of simple modifications (like setting a single value).

In any case I do not have time to implement either solution, but if someone does want to work on this, I tried to give some guidance on #300 and actually trying to code it would probably reveal some more insights.

**Comment by havocp** [comment]
Keeping formatting really would make a mess of Config's implementation too, due to withFallback for example. A Config normally represents the merger of multiple files and properties, perhaps some manual modifications, and may not come from a file at all... so making it track syntax gets messy fast. It's mixing concerns into a big ball of mud. That's why ConfigDocument is separate.

Improving ConfigDocument involves a bunch of classes due to all the types of node, typing all that in and writing some tests would be a bit tedious, but I don't think there's anything conceptually hard or algorithmically tricky.

**Comment by FerusGrim** [comment]
This issue was resolved on the other end.
