### ISSUE TITLE
Repo was moved to lightbend/... github

### ISSUE THREAD

**Issue by ktoso** [lightbend/config#509]
Hi @havocp,
Wanted to let you know we're cleaning up repositories and moved this one and other actively maintained repos from `typesafehub/` to `lightbend/` all things should work fine, and if people go to https://github.com/typesafehub/config they'll be redirected nicely. 

I hope the move is fine with you! I've given you full admin rights of course. We're not intending to change naming or anything in the library, it's perfectly fine with how it is - just wanted to move actual active projects onto the actual active github account rather than the archive/dumping-ground that typesafehub has become over the years.

**Comment by havocp** [comment]
Sounds good!

**Comment by havocp** [comment]
(Thanks for keeping me in the loop - not that I've been doing a ton of useful stuff, but I do sort of try to read the github traffic and reply to things.)

**Comment by 2m** [comment]
I see there are some more links to typesafehub sprinkled around the files in the repo. I'll replace them to lightbend right now.

**Comment by 2m** [comment]
We need to either move the chatroom to https://gitter.im/lightbend/config if possible or close the old one and start the new one.

**Comment by havocp** [comment]
It looks like I don't have write perms anymore fwiw (went to merge https://github.com/lightbend/config/pull/511 and could not)

**Comment by 2m** [comment]
@havocp try now. There might be an invitation that you need to accept.

**Comment by ktoso** [comment]
Had to upgrade our number of "seats", added you as admin in the "config" team now, you may need to accept an invitation (email) @havocp

**Comment by dwijnand** [comment]
@2m I think you can contact Gitter to rename the room. We did that to rename from sbt/sbt-dev to sbt/sbt-contrib.

**Comment by 2m** [comment]
Thanks. Dropped them a message.

**Comment by SethTisue** [comment]
issue on the possibility of renaming the library entirely: #514

**Comment by SethTisue** [comment]
> I think you can contact Gitter to rename the room

@2m the instructions on this are at https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo

the first step, before contacting Gitter, is to make a room under the new org

**Comment by 2m** [comment]
I have contacted gitter already. They only asked to create a community. Will see what their response is going to be.

**Comment by ben-manes** [comment]
Note that the repository rename broke JavaDoc links for the released artifacts.

```
javadoc: warning - Error fetching URL: http://typesafehub.github.com/config/latest/api/
```

**Comment by SethTisue** [comment]
@2m any response from Gitter?

@ben-manes sorry about that... @havocp is it worth rolling a new release to fix those links?

**Comment by ben-manes** [comment]
Maybe switch to javadoc.io for hosting?

**Comment by 2m** [comment]
Chatroom has been successfully moved to https://gitter.im/lightbend/config

**Comment by SethTisue** [comment]
afaict the only remaining todo here was the Javadoc thing, so I opened #530 on that, closing this one
