### ISSUE TITLE
Filter/Replace critical information like passwords when using render

### ISSUE THREAD

**Issue by danischroeter** [lightbend/config#512]
Typesafe configs ability to render the config is supernice. 
We want to provide a machines config on an http endpoint for easier debug. However things that are critical like passwords should be replaced by **** or something.

Because of the way the config is implemented currently it is not easy to filter the config and then render.
It would be nice to have the ability to add a custom formatter to RenderOptions or something similar.

Opinions on this idea and implementation ideas very much appreciated...

**Comment by havocp** [comment]
Maybe withoutPath? https://lightbend.github.io/config/latest/api/com/typesafe/config/Config.html#withoutPath-java.lang.String-

Config has no way to know what's a secret (since it has no schemas), so it's tough to do much automatically here.

**Comment by wsargent** [comment]
Possible inspiration (I don't think HOCON uses Jackson internally, oh well): this is something that can be done in Jackson by using the JsonGeneratorDecorator and JsonGeneratorDelegate / FilteringGeneratorDelegate see https://github.com/FasterXML/jackson-core/issues/185 for more details.  You specify the key, and then it swaps out the tree.

**Comment by danischroeter** [comment]
solved by using a regex to filter the rendered config...

```
object JasoConfigRender {
  private val regex = s"""((?:[\w]+-password|password|secret)\\s*:\\s*").*"""".r

  def renderFilteringPasswords(configToRender: Config): String = {
    val renderedConfig = configToRender.root().render(ConfigRenderOptions.defaults())
    regex.replaceAllIn(renderedConfig, r => r.group(1) + "***\"")
  }
}
```
