### ISSUE TITLE
Unexpectedly quoted keys

### ISSUE THREAD

**Issue by eshu** [lightbend/config#524]
I do not think it is a correct behaviour to quote keys that contains special characters like brackets. Here is a test written on Scala:
```scala
import com.typesafe.config.ConfigFactory
import org.scalatest.FunSpec

import scala.collection.JavaConversions._

class ConfigTest extends FunSpec {
  describe("Config") {
    it("should return unquoted key") {
      assertResult("sum(n)") {
        ConfigFactory.parseString("sum(n): \"sum\"").entrySet.head.getKey
      }
    }
  }
}
```

The output is:
`
Expected "[sum(n)]", but got "["sum(n)"]"
`

It seems breaking the principle of least astonishment. :)

**Comment by havocp** [comment]
From a correctness standpoint the keys in Config.entrySet are path expressions (see docs), so they always _can_ be quoted, and sometimes _must_ be quoted if they contain chars that must be quoted according to HOCON. For implementation see https://github.com/lightbend/config/blob/b5578f40836f75d3e91ab7780deae8039fbfe82d/config/src/main/java/com/typesafe/config/impl/Path.java#L178

The code currently quotes more than it has to, it’s true, but I think this is only a cosmetic issue.
The correctness rule is that parsing this as a path has to give back the original list of keys. 

I suppose we could add more chars that are allowed unquoted but application code should not rely on that.

**Comment by eshu** [comment]
Maybe it would be good to add a flag to ConfigParseOptions option that prevents keys quotation? Or maybe a special character that prevents this behaviour for some keys? For example, `sum(n)` should be quoted and `` `sum(n)` `` should not

**Comment by havocp** [comment]
What’s the use case? Would like to understand why this is important to you. 

fwiw the ConfigDocument API (when/if completed) is intended to preserve and allow control of formatting. The Config object isn’t set
up to support that.

**Comment by eshu** [comment]
Briefly I have two ways to configure how to rename column in the table:
```
rename-columns {
  sum(n): sum
  count(1): count
}
```
and
```
rename-columns = [
  { name = "sum(n)", new-name = "sum" }.
  { name = "count(1)", new-name = "count" }
]
```
I think the first one is more laconic and have lesser chances to make an error with duplicate columns.

**Comment by havocp** [comment]
I don’t understand why the rendered string matters for that though?

Maybe you are missing ConfigUtils.splitPath to parse path expressions ?

**Comment by eshu** [comment]
In this code
```
cfg.getConfigList("renameColumns").entrySet.foreach({ case (name, newName) => table.renameColumn(name, newName) })
```
I trying to rename columns with first config and this code does not work if I receive quoted key `"sum(n)"` instead unquoted `sum(n)`, for example.

I think this quotation is useless in any case. Why somebody may want it? Is there any use case for it?

**Comment by havocp** [comment]
Here your code is not correct unless you use splitPath to parse the path expression.

There is a section explaining this more in the overview of Config in the API docs. (paths vs keys)

For what you’re expecting here, ConfigObject has those semantics, rather than Config

**Comment by havocp** [comment]
See http://lightbend.github.io/config/latest/api/com/typesafe/config/Config.html "Paths, keys, and Config vs. ConfigObject"

**Comment by eshu** [comment]
Yes, seems like ConfigObject works in this case. Sorry for late reply, thank you very much!
