### ISSUE TITLE
Cannot parse with `ClassNotFoundException: scala.Int`

### ISSUE THREAD

**Issue by seoh** [lightbend/config#528]
I made a sbt project(1.0.3, and dont know which verion of config is used) and get an error. but switched to 0.13.16, and it solved. (maybe same issue. https://github.com/typesafehub/sbteclipse/issues/348)

I minimalize a project and tried to reproduct, but cannot figure out any more. in sbt 1.0, I got this error(https://github.com/seoh/bug-FactoryConfig/blob/master/sbt-1.0.log).

but I got an interested case. with sbt 1.0, but it works in IntelliJ. I have no idea which enviroment is different. I need some help to get closed to this problem.

**Comment by raboof** [comment]
hello @seoh - this does not look like a Typesafe Config problem. Perhaps this might be something to ask on stackoverflow? Are you running from SBT directly, or also using an IDE? Do you get the same problem when you use only sbt? (make sure to 'clean')

**Comment by raboof** [comment]
Thanks for sharing that example project. I'm pretty confident that it has nothing to do with Typesafe Config, but it's not quite obvious where the problem is, so I'll look into it a bit.

**Comment by raboof** [comment]
I have boiled it down to https://github.com/raboof/sbt-run-classloading/blob/master/src/main/scala/Main.scala - definitely not a typesafe config issue, but possibly sbt (or akka). I've asked in the sbt [gitter channel](https://gitter.im/sbt/sbt) for starters.

**Comment by raboof** [comment]
I have opened https://github.com/sbt/sbt/issues/3736

**Comment by seoh** [comment]
I dont know how config works in sbt and I am not sure for same issue, but same exception at same source file and line. Thanks for your effort. I close this issue and keep tracking sbt issue.
