### ISSUE TITLE
repository org change broke Javadoc hosting

### ISSUE THREAD

**Issue by SethTisue** [lightbend/config#530]
reported by @ben-manes at https://github.com/lightbend/config/issues/509#issuecomment-340578300

 @havocp is it worth rolling a new release to fix those links?

**Comment by havocp** [comment]
I'd be fine with a release for this if someone can take it on, but not sure when I could get to it myself :-/

**Comment by ktoso** [comment]
We'll get to it 👍

**Comment by dwijnand** [comment]
Duplicate of #516
