### ISSUE TITLE
Null values in config

### ISSUE THREAD

**Issue by eshu** [lightbend/config#537]
Seems like unexpected behaviour: if I try to do `ConfigFactory.parseString("key = null").getValue("key")` then I receive exception "Configuration key 'key' is null" instead `ConfigValue` with `valueType == ConfigValueType.NULL`

https://github.com/lightbend/config/blob/eeb95825bf3763959ddd073d20b11045d2c01131/config/src/main/java/com/typesafe/config/impl/SimpleConfig.java#L207

**Comment by havocp** [comment]
value type of null appears only in ConfigObject not Config. See the discussion of those two interfaces in the api docs and readme.
