### ISSUE TITLE
Please provide syntax highlighting for common editors

### ISSUE THREAD

**Issue by mrubin** [lightbend/config#542]
Please provide syntax highlighting files for this language for popular editors.

**Comment by raboof** [comment]
A quick search suggests there's already highlighting for editors such as [Sublime](https://packagecontrol.io/packages/HOCON%20Syntax%20Highlighting), [VsCode](https://github.com/sabieber/vscode-hocon), [Atom](https://atom.io/packages/language-hocon) and [IntellIJ](https://www.jetbrains.com/help/idea/code-style-hocon.html).

What editors would you be particularly interested in?

**Comment by mrubin** [comment]
Thanks for the quick response. I was interested in Sublime and the link you referenced did not work through Sublime itself - so I assumed the package didn't exist. However, it worked when installed manually. That package looks to be 4 years old, maybe it is outdated and no longer installs from within Sublime.

**Comment by raboof** [comment]
Cool! I'm not familiar with Sublime myself but I guess you could bring it up at https://github.com/NeQuissimus/Sublime-Hocon ?
