### ISSUE TITLE
Publish with stable JDK9 module name

### ISSUE THREAD

**Issue by jroper** [lightbend/config#546]
Typesafe config currently gets an automatic module name of `config`, since the artifact name is config. This is a recipe for conflict. This can be solved by adding an `Automatic-Module-Name` attribute to the jar manifest. I suggest we name it `com.typesafe.config`, or just `typesafe.config`.

**Comment by ktoso** [comment]
1.3.3 was released @jroper @havocp @2m  :)

**Comment by havocp** [comment]
@ktoso can you add a note to NEWS.md ?   ( release steps in https://github.com/lightbend/config/blob/master/CONTRIBUTING.md of course) thanks!

**Comment by ktoso** [comment]
Man, sorry for missing process, will follow up steps
