### ISSUE TITLE
List of config  in withFallBack

### ISSUE THREAD

**Issue by tgupta1419** [lightbend/config#554]
I have a java List<Config> and I want to get a ConfigList so I do:

`List<Config> dbConfig`
ConfigList configList = ConfigValueFactory.fromIterable(dbConfig);
- the above statement throws and exception. 
The reason I do a ConfigList is to provide the configList to .withFallBack to get the merged configs.
How do i make this work with the library.

**Comment by havocp** [comment]
It doesn't make sense to do this afaik. A list isn't a config because it's only a value. Configs are path-value pairs.

What would make sense is to put the list in a Config:
 ``` java
Config myFallback = ConfigFactory.empty().withValue("my.path", listValue);
Config config = ConfigFactory.parseFile(file).withFallback(myFallback);
```

Closing issue because it's a question not an issue, but feel free to discuss further here or join the chat.
