### ISSUE TITLE
Feature: Support indirect variable reference

### ISSUE THREAD

**Issue by jgogstad** [lightbend/config#558]
From bash we're used to
```
a=b
b=foo
c=${!a}
echo c // outputs foo
```

It would be nice to be able to reference variables indirectly like this in HOCON.

**Comment by havocp** [comment]
Perhaps the same request as https://github.com/lightbend/config/issues/134 ?

**Comment by jgogstad** [comment]
Agree, closing.

**Comment by havocp** [comment]
thanks!
