### ISSUE TITLE
Nested configuration from environment variables

### ISSUE THREAD

**Issue by tinchou** [lightbend/config#559]
I'm trying to allow users to set configuration through environment variables (specially helpful in dockerized environments) but the library doesn't pick up the values I'm setting.

Before, we were using System Properties (e.g. `-Drpc.providers.web.http.bind_address=hostname`) and it worked just fine.

Then I tried setting the same configuration through environment variables and reading it with the following:

```java
Config config = ConfigFactory.systemProperties()
                .withFallback(ConfigFactory.systemEnvironment())
                .withFallback(baseProperties);
```

When I call `config.getString("rpc.providers.web.http.bind_address")` I don't get the value of my environment variable, but the default value I had in `baseProperties`.The library seems to fail to detect nested properties as seen in the debugger:

![image](https://user-images.githubusercontent.com/1548532/40857861-d4248b60-65b2-11e8-9db3-5671e54fefcd.png)

I'm guessing there might be an assumption that env vars can't have dots in them, but I haven't had the time to check the code yet.

I'm using `com.typesafe:config:1.3.1`.

Thanks!

**Comment by havocp** [comment]
Version 1.3.2 has the fix you need I think: https://github.com/lightbend/config/pull/427

**Comment by tinchou** [comment]
It works! Sorry for the spam :)
