### ISSUE TITLE
Dynamically calculate value?

### ISSUE THREAD

**Issue by herzrasen** [lightbend/config#562]
Hi,

is it possible to dynamically calculate a substitution value? 

For example:
`{
  a.b = ${?NUM/2+1}
}
`

So that the substitute would be the value of NUM divided by 2 and incremented by 1?

**Comment by havocp** [comment]
No - the line we’ve drawn is “no code-like logic.” There is a thing called Jsonnet that does stuff like that though. https://blog.ometer.com/2015/09/07/json-like-config-a-spectrum-of-underoverengineering/

**Comment by herzrasen** [comment]
Ok, thanks for the reply. I perfectly understand the line you have drawn.
