### ISSUE TITLE
Parsing manually from a resource does not resolve System property

### ISSUE THREAD

**Issue by yerlibilgin** [lightbend/config#563]
Parsing manually from a resource does not resolve System property
The Code:

```
InputStream resourceStream = this.getClass().getResourceAsStream("/resource.txt");
Config config = ConfigFactory.parseReader(new InputStreamReader(resourceStream)).resolve();
config.getString("some.thing);
```

Run command:

```
export JAVA_OPTS="${JAVA_OPTS} -Dsome.thing=hello"
java -jar jarname.jar
```

Output:

```
Caused by: com.typesafe.config.ConfigException$Missing: 
No configuration setting found for key 'some'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
```

Version: `"com.typesafe" % "config" % "1.3.2"`

OS: MacOS High Sierra 10.13.3
Java version:  
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by havocp** [comment]
The system properties have to be merged in `withFallback(ConfigFactory.systemProperties())` I think, something like that not sure about method name. Or reverse it to make system properties override instead of fallback.

ConfigFactory.load is doing this for you see API docs for what it does.

**Comment by havocp** [comment]
What you might want is the variant of ConfigFactory.load that takes a Config parameter and sandwiches it in the usual defaults and overrides.

**Comment by yerlibilgin** [comment]
Having tried that (after that much of long time), I confirm that it works with `withFallback...` but the problem here is that unwanted properties are also introduced. Only including the values that are declared in the config file would make more sense (and let out the ones that aren't). But as this should be another issue, I am closing this one
