### ISSUE TITLE
Clarify note that apps should not use reference.conf but application.conf

### ISSUE THREAD

**Issue by ktoso** [lightbend/config#575]
The note 

> (Applications can provide a reference.conf also if they want, but you may not find it necessary to separate it from application.conf.)

In "standard behavior" section is a bit confusing to people it seems as I've seen a group use only reference.conf in their applications and it happened to work since it ended up last on classpath but we know that's  a bad idea (they did not use application.conf).

I propose to remove the wording about apps MAY provide reference conf since it seems it could have led people to believe that the reference.conf was enough for them

**Comment by havocp** [comment]
I played with rewording the sentence just now but maybe it’s fine to simply delete it?

**Comment by ktoso** [comment]
Yeah I think removing it would achieve the effect we're after as well, can PR that once I'm out of customer meetings today :)
