### ISSUE TITLE
Q: Is there any way to get the location of a config key.

### ISSUE THREAD

**Issue by artyomkorzun** [lightbend/config#580]
I have the following piece of code:
```
ConfigParseOptions defaultDescription = ConfigParseOptions.defaults()
                .setOriginDescription("default-config");

Config defaultConfig = ConfigFactory.parseString("service.default = DEFAULT", defaultDescription)
                .resolve();

ConfigParseOptions description = ConfigParseOptions.defaults()
                .setOriginDescription("config");

Config config = ConfigFactory.parseString("services.some = ${service.default}", description)
                .withFallback(defaultConfig)
                .resolve();

String location = config.getValue("services.some").origin().description();  // points to the default
```
I want to check a config key to meet some requirements.
For example, it should be an upper-case text value.
If it isn't I warn with pointing to the file location.

Is there any way to get the location of a config key?

Thank you.

**Comment by havocp** [comment]
config.getValue().origin() should work for this

**Comment by artyomkorzun** [comment]
It definitely works but returns the location of the default config. 
But the key is placed in the actual (not default) config.

`System.out.println(location); // > default-config: 1`

I need the actual location.

**Comment by havocp** [comment]
Ah, sorry, I didn't read carefully enough. Locations are only stored on values and not keys, so short answer I don't think there's a way to do this.

**Comment by artyomkorzun** [comment]
Ok. Thak you for clarification.
