### ISSUE TITLE
Missing line number when settings key not found

### ISSUE THREAD

**Issue by ensirius** [lightbend/config#584]
Hello!

For example, when i trying to get settings key with wrong type i am getting the following exception:

`com.typesafe.config.ConfigException$WrongType: test.conf: 51: X has type STRING rather than NUMBER`

But if settings key are missing i am getting:

`com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'X'`

It's possible to show the root config number line:

```java
Position { 
    D: 10, Y: -10, Z: 0
}
```

```java
config.getConfig("Position").getDouble("X");
```

`com.typesafe.config.ConfigException$Missing: test.conf: 50: No configuration setting found for key 'X'`

**Comment by havocp** [comment]
In normal use the Config object would be a combination of multiple files, system props and env vars, so it’s hard to say which of those was missing the setting - they were all missing it.

That said there may be a way to add the file in certain contexts, would need exploring.
