### ISSUE TITLE
New minor relase?

### ISSUE THREAD

**Issue by vagola** [lightbend/config#609]
Since last release passed almot a year.

**Comment by Veske** [comment]
But why?

**Comment by zachbr** [comment]
I too would like to see a minor release relatively soon. Fixes like https://github.com/michalmela/config/commit/fee9a3e80e971760b7cff62f2e02a89473081af3 would be nice to get into downstream projects that rely on stable releases.

After an entire year I'm sure there are numerous other fixes and improvements that others would like to see.

**Comment by Philippus** [comment]
solved by https://github.com/lightbend/config/releases/tag/v1.3.4

**Comment by 2m** [comment]
Thanks!
