### ISSUE TITLE
`section.foo = ${?FOO}` creates empty `section{}`

### ISSUE THREAD

**Issue by folex** [lightbend/config#615]
I have a config application.conf:
```hocon
section.foo = ${?FOO}
```

Reading [README](https://github.com/lightbend/config#optional-system-or-env-variable-overrides):
```
basedir = "/whatever/whatever"
basedir = ${?FORCED_BASEDIR}
```
> Here, the override field basedir = ${?FORCED_BASEDIR} simply vanishes if there's no value for FORCED_BASEDIR, but if you set an environment variable FORCED_BASEDIR for example, it would be used.

**I expect** the whole line `section.foo = ${?FOO}` to vanish. 

But instead **I see**: `Config(SimpleConfigObject({"section":{}}))`.

It's reproducible as a scala one-liner (well, two):
```scala
import com.typesafe.config._

ConfigFactory.load(ConfigFactory.parseString("section.foo = ${?FOO}")).getValue("section")

res0: com.typesafe.config.ConfigValue = SimpleConfigObject({})
```

One implication of this is when I'm using something like pureconfig which automatically generates a case class from `typesafe.config.Config` like the following:

```scala
// config DTOs
case class Section(foo: String)
case class MyConfig(section: Option[Section])
```

Then when I try to parse `section.foo = ${?FOO}` to `MyConfig`, I will get an exception saying that `foo` wasn't found.  But I would intuitively expect the whole `section` to be `None`.

**Comment by havocp** [comment]
I believe the spec and implementation both are that `section.foo = ${?FOO}` is exactly the same (syntactic sugar for) `section : { foo : ${?FOO} }` - with the more-expanded syntax, maybe it's clearer why this happens. `foo : ${?FOO}` does indeed vanish, but what's left is `section : {}`, rather than nothing at all.

**Comment by folex** [comment]
Thanks for such a quick answer!

Well, if that's an expected behaviour, then I'll try to find some workaround. 

But I wish there would be a way to prevent generation of `section{}` in case all of its content is built from optional env variables which all happened to be undefined :)

Feel free to close the issue. Thanks once more.

**Comment by havocp** [comment]
You are welcome. Maybe there’s a feature idea here ... needs some thought.
