### ISSUE TITLE
How the Env config substitution works

### ISSUE THREAD

**Issue by im-naren** [lightbend/config#630]
I am not able to substitute the env variables in `application.properties`

maven dependency:
``` 
<dependency>
    <groupId>com.typesafe</groupId>
    <artifactId>config</artifactId>
    <version>1.3.4</version>
</dependency>
```

`application.properties` present in resources
`test=${FORCED_VARIABLE}`

Code:
```
var config = ConfigFactory.load()
println(System.getenv("FORCED_VARIABLE"))
println(config.resolve().getString("test"))
```

output:
```
test_value
${FORCED_VARIABLE}
```

I am new to scala world, please suggest me what is that i am doing wrong

**Comment by havocp** [comment]
`${}` syntax is a feature of the .conf file format while .properties files are the traditional Java format. Name your file application.conf and it will work I think.
