### ISSUE TITLE
Environment substitution does not work

### ISSUE THREAD

**Issue by nemoo** [lightbend/config#633]
Expected behaviour: 
According to the lightbend/config documentation: ${HOME} would work as you expect.

Actual behaviour: 
I want to provide the host part of the slick db url from an environment variable in a playframework application.conf file:

slick.dbs.default.db.url="jdbc:postgresql://${X_POSTGRES_HOST}:5432"
When I run the application, config just will not resolve the environment variable X_POSTGRES_HOST.

Slick expects a String in slick.dbs.default.db.url, but if I provide a String with quotes like shown above, the environment variable will not be resolved by lightbend config.

**Comment by havocp** [comment]
Substitution only happens outside quotes. This is a JSON superset, so quoted strings have the same meaning as in JSON. write it as `”text“${HOST}”moretext”`

**Comment by nemoo** [comment]
Thanks for the information! Please add this to the documentation. In a containerized world, more and more people will need to substitute environment variables into strings.

**Comment by TimMoore** [comment]
It is already in the documentation:

https://github.com/lightbend/config/blob/master/HOCON.md#substitutions

> Substitutions are not parsed inside quoted strings. To get a
string containing a substitution, you must use value concatenation
with the substitution in the unquoted portion:
> 
>     key : ${animal.favorite} is my favorite animal
> 
> Or you could quote the non-substitution portion:
> 
>     key : ${animal.favorite}" is my favorite animal"

**Comment by havocp** [comment]
https://github.com/lightbend/config/pull/634

**Comment by elkhart** [comment]
@TimMoore You're right about the docs part but from the first read it looked like only prefixing is allowed. I think an example like the one above ”text“${HOST}”moretext” would help a lot in the docs

**Comment by TimMoore** [comment]
@elkhart could you raise a new issue (and ideally a pull request) for updating the doc example please?
