### ISSUE TITLE
Writing support?

### ISSUE THREAD

**Issue by Buckstabue** [lightbend/config#645]
Does it support writing configs? If so, could you please add an example in the readme

**Comment by havocp** [comment]
Generally no; there's a render() method to get a config as a string, so you can write that out, but for example formatting isn't preserved if you load and re-save.

**Comment by winflex** [comment]
> Generally no; there's a render() method to get a config as a string, so you can write that out, but for example formatting isn't preserved if you load and re-save.

Where is this render() method?  Which class?
