### ISSUE TITLE
Self-references don't pull in environment variables

### ISSUE THREAD

**Issue by anujkumar93** [lightbend/config#652]
I am trying to accomplish a simple task which is to pull in an environment variable `MYVAR` into my generated pyhocon config. I have executed `export MYVAR=my_value` in my env.

I have the following in my `pyhocon_test.conf`:
```
MYVAR : ${MYVAR}
```
This raises the following error:
```
pyhocon.exceptions.ConfigSubstitutionException: Cannot resolve ${MYVAR}: (line: 1, col: 9). Check for cycles.
```

I know from the documentation that self-references work. Having the following in my conf file
```
MYVAR=2
MYVAR : ${MYVAR}
```
will give me the correct output `ConfigTree([('MYVAR', 2)])`.

I know environment variable substitutions also work. Having the following conf:
```
SECOND_VAR : ${MYVAR}
```
also gives the expected substituted output: `ConfigTree([('SECOND_VAR', 'my_value')])`.

I am unable to make them both work well together. My expected outcome is to pull in the environment variable without editing the key: `ConfigTree([('MYVAR', 'my_value')])`. I'm using `pyhocon==0.3.51` inside Python3.6 environment.

**Comment by havocp** [comment]
I’m not familiar with pyhocon’s implementation details, but this should work I believe and I think does with the Java implementation.

This part of the spec is pretty hairy to implement and one of the things I think a reimplementation would probably have to do a lot of work to get right.

**Comment by anujkumar93** [comment]
@havocp Oh sorry, my bad. Somehow following the trail of documentation, I ended up in this repo, and opened an issue here. Closing this after opening it in pyhocon repo: https://github.com/chimpler/pyhocon/issues/213
