### ISSUE TITLE
Environment substitution feature unclear

### ISSUE THREAD

**Issue by IRobL** [lightbend/config#656]
| substitutions fall back to environment variables if they don't resolve in the config itself, so ${HOME} would work as you expect. Also, most configs have system properties merged in so you could use ${user.home}.

I'm not sure how to populate configurations into my app via the system's environment variables.  Is this not meant to work:

```
app {
  name = "${NAME}"
}
```

```
NAME=fred java -jar build/libs/app.jar 
HERES DATA: ${NAME}
```

**Comment by havocp** [comment]
HOCON is a JSON superset, so `"${NAME}"` is the literal string `"${NAME}"` just as in JSON.
To get environment substitution remove the quotes and it should work

**Comment by IRobL** [comment]
That fixed everything, thanks!
