### ISSUE TITLE
Application and Reference Config Files not Merging When Building JAR for Deployment

### ISSUE THREAD

**Issue by KookyLukey** [lightbend/config#657]
I have an sbt application that will run when ran through intellij or through the terminal using `sbt run`. However, when I create a fat jar to be able to deploy, I get all kinds of `com.typesafe.config.ConfigException$UnresolvedSubstitution` errors. They aren't user defined ones in my application conf, they are all the ones that I assume are defined in the akka conf files.

I have tried merging them using the below:

`val config = ConfigFactory.load(getClass().getClassLoader())`
```
private lazy val userConfig = ConfigFactory.parseResources("application.conf")
val config = userConfig.resolve()
```
```
 mergeStrategy in assembly := {
   case PathList("reference.conf") => MergeStrategy.concat
   case "reference.conf" => MergeStrategy.concat
   case "application.conf" => MergeStrategy.concat
   case x if x.contains("akka\\http\\") => MergeStrategy.concat
   case x if x.contains("akka/http/") => MergeStrategy.concat
```
I have also tried to hardcode whatever value it complains about in my application.conf, that will resolve it, but then it will just complain about a different variable that it can't resolve. Rinse and repeat.

**Comment by havocp** [comment]
It sounds like your fat jar isn’t ending up with all the reference.conf in the right place
but it isnt obvious to me why. StackOverflow would probably have a lot more people who’d be likely to know

**Comment by KookyLukey** [comment]
Turns out IntelliJ isn't the best at building fat jars. I was able to resolve it using `sbt assembly` to build the jar instead. Thanks for the help @havocp
