### ISSUE TITLE
key with dot issue when parsing json

### ISSUE THREAD

**Issue by archieby** [lightbend/config#668]
I find the fact that the following example fails with an error a bit confusing:
```
ConfigFactory.parseString("{\"user.name\":\"xxx\"}")
   .getString("user.name")
```

```
No configuration setting found for key 'user'
```

The following syntax works:
```
ConfigFactory.parseString("{\"user\": {\"name\": \"xxx\"}}").getString("user.name")
```
but I believe that the dot is an allowed JSON character, but I'm not able to extract value by the valid key.
Is there any way to make it work? M.b. some `ConfigParseOptions`?

**Comment by havocp** [comment]
Don’t put quotes on `user.name`; hocon doesnt change the meaning of existing json syntax such as quoted strings

**Comment by raboof** [comment]
The question is whether you really want a key named "user.name" (with the dot). If so, you do need the quotes around the key.

In that case it's useful to understand that `getString` takes a `path`, not a `key`, so you have to quote the key in the path as well (to avoid the dot from being interpreted): `config.getString("\"user.name\"")`

**Comment by archieby** [comment]
@raboof thanks a lot!
That actually worked
