### ISSUE TITLE
Convert conf file to JAVA Custom class object

### ISSUE THREAD

**Issue by hemantpandey17** [lightbend/config#673]
I have been trying to convert my config file into an object of a Java POJO class.
The config file is a HOCON file :

{
"records": [
{
firstName= "Hemant"
lastName="Pandey"
Age=25
},
{
firstName= "Vaashu"
lastName="Sharma"
Age=24
}
]
}

The POJO class too has same members as firstname, lastName and Age.
I tried getting a configList which creates a Java Object list.

Config conf = ConfigFactory.load("configFile");
    	List<? extends Config> records = conf.getConfigList("records");
    	for (Config record : records) {
    		Person rec = new Person();
    		rec.setFirstName(record.getString("firstname"));
    		rec.setLastName(record.getString("lastName"));
.....

Is there a better way to do this using lambdas etc ?

**Comment by radist-nt** [comment]
may be you need ConfigBeanFactory?

**Comment by hemantpandey17** [comment]
> may be you need ConfigBeanFactory?

Yes, that was exactly what I needed :D
