### ISSUE TITLE
Config File Merge: Resolution Order

### ISSUE THREAD

**Issue by godenji** [lightbend/config#680]
Just upgraded a Play application from v2.6 to 2.8; seems like something happened with config file resolution order.

Given an sbt project structure like A -> B -> C, each with their own `application.conf`, merge priority looks like C -> B -> A.

Not sure if this is a change in sbt wrt `ProjectRef`s, or if it's an issue with Lightbend config (EDIT: version of Play, 2.6.19, used 1.3.3 ~I see the recent `reference.conf` merged PR as the only significant change between 1.3.4 and 1.4.0~ ), but as it stands things are completely backward of what one would expect (not to mention completely breaking the app).

Note: tried downgrading to Play 2.7 to see if something changed in Play; same result. Similarly, downgrading from sbt 1.3.10 to 1.2.8 brought the same result.

I'll see if I can reproduce in a minimal project.

**Comment by godenji** [comment]
Here's a minimal repro: https://github.com/godenji/play-config-merge

**Comment by havocp** [comment]
I think this would be an sbt or Play change; all the config library does is call standard Java APIs to get the list of resources called application.conf on the classpath, and leaves them in the order they were returned in. I would guess that if you print out the classpath in 2.6 vs. 2.8, it is reordered.

**Comment by godenji** [comment]
Ok, I'll close this and open an issue with Play.
