### ISSUE TITLE
[Feature Request] Add a flag or a way to make `required` the default behavior for `include`

### ISSUE THREAD

**Issue by floating-cat** [lightbend/config#683]
As Johnlon mentioned here: https://github.com/lightbend/config/issues/121#issuecomment-243925416
> One thing we discussed a way back was whether the java api should allow us to make "required" the default if that's what you want.

Could we add a flag or a way to make `required` the default behavior for `include`? An included file could be missing as a default behavior seems a bad idea to me. I always write the `required` in my configurations.
Also, I would like to see `include optional("a-file.conf")` after enabling this flag and making the `requried` default  (I am not sure whether this suggestion is a good idea though).

**Comment by radist-nt** [comment]
You can use `ConfigParseOptions.defaults().setAllowMissing(false)`, but the option is not inherited for nesting includes (I think, this is strange behavior, but it's documented).
To force this option for nesting includes, you can specify the Includer:
```
private static class RequiredIncluder implements ConfigIncluder {

	private ConfigIncluder delegate;

	@Override
	public ConfigIncluder withFallback(ConfigIncluder fallback) {
		Objects.requireNonNull(fallback);
		if (delegate != fallback) {
			if (delegate == null)
				delegate = fallback;
			else
				delegate = delegate.withFallback(fallback);
		}
		return this;
	}

	@Override
	public ConfigObject include(ConfigIncludeContext context, String what) {
		Objects.requireNonNull(delegate, "ConfigIncluder not accessible");
		context = context.setParseOptions(context.parseOptions().setAllowMissing(false));
		return delegate.include(context, what);
	}
}
```

It will work with `include "xxx"` but not with `include file("xxx")`. To inherit allowMissing flag for any includes, you have to implement additional interfaces: ConfigIncluderClasspath, ConfigIncluderFile, ConfigIncluderURL, here is an example:
```
	@Override
	public ConfigObject includeURL(ConfigIncludeContext context, URL what) {
		Objects.requireNonNull(delegate, "ConfigIncluder not accessible");
		context = context.setParseOptions(context.parseOptions().setAllowMissing(false));
		if (delegate instanceof ConfigIncluderURL)
			return ((ConfigIncluderURL) delegate).includeURL(context, what);
		else
			return ConfigFactory.parseURL(what, context.parseOptions()).root();
	}
```
