### ISSUE TITLE
Release 1.4.1?

### ISSUE THREAD

**Issue by swaraj2204** [lightbend/config#702]
Hi,

When can I expect a new release as I see from last year Oct-2019 there is no further release.

**Comment by raboof** [comment]
If lightbend credentials are still needed, if someone can update the NEWS.md and README.md I can do the other tasks of https://github.com/lightbend/config/blob/master/RELEASING.md

**Comment by swaraj2204** [comment]
What are the issues need to be updated in NEWS.md

**Comment by extbe** [comment]
@swaraj2204 can you update the NEWS.md or could I do it myself?

**Comment by swaraj2204** [comment]
Sure

> @swaraj2204 can you update the NEWS.md or could I do it myself?

**Comment by swaraj2204** [comment]
https://github.com/lightbend/config/pull/707

**Comment by havocp** [comment]
Just merged #708 as well

**Comment by extbe** [comment]
@swaraj2204 could you add a new resolved issue to the PR?

**Comment by mkurz** [comment]
@extbe Which one? #708 was added to #707 already.

**Comment by extbe** [comment]
I didn't notice that :sweat_smile:

**Comment by extbe** [comment]
is there anything else that has to be done before releasing a new version?

**Comment by extbe** [comment]
Can I somehow speed up the release of the new version?

**Comment by andreaTP** [comment]
Just finished releasing `1.4.1`! 🎉
