### ISSUE TITLE
Substitution error (substitution is not resolved)

### ISSUE THREAD

**Issue by lospejos** [lightbend/config#719]
I've created a small demo project here: https://github.com/lospejos/lightbend-config-example

In this project I have a two config parameters in `src/main/resources/application.conf`:
- `db_server` which has default value `database` and may be overriden by environment variable `DB_SERVER`
- `db_url` which has substitutuion like this: `jdbc:postgresql://${db_server}/db_name?params` (note `${db_server}` inside)

When I start application, I expect to see output:

If I do not set environment variable `DB_SERVER`:
```
db_server = database
db_url = jdbc:postgresql://database/db_name?params
```

If I do set environment variable `DB_SERVER` to f.e. `mysrv1`:
```
db_server = database
db_url = jdbc:postgresql://mysrv1/db_name?params
```

But actually I see output (note not resolved / substituted `${db_server}` in output string):

```
db_server = database
db_url = jdbc:postgresql://${db_server}/db_name?params
```

Am I missing something? How should I change my project to get expected results? Thanks.

**Comment by havocp** [comment]
See https://github.com/lightbend/config/issues/633 I think?

**Comment by lospejos** [comment]
> 
> 
> See #633 I think?

Yes, thanks, you're right, I was inattentive. I close this issue.

**Comment by lospejos** [comment]
For the benefit of others: in short, substitution happens outside double quotes. In my case this worked (note quotes outside of `${db_server}`):
```
db_server = database
db_server = ${?DB_SERVER}
db_url = "jdbc:postgresql://"${db_server}"/db_name?params"
```
