### ISSUE TITLE
Change inheritance behavior from concatenation to override when switching from : to =

### ISSUE THREAD

**Issue by advhscmoe** [lightbend/config#726]
Is it possible for hocon parsing to treat = slightly different from :, namely instead of doing concatenation, simply override the subfield, during nested inheritance, as the following example illustrates?

Starting from one of the following three config files:

```
a: {
  b: {
    c: 1
  }
}
d: ${a} {
  b = {
    d: 2
  }
}
```
or 
```
a: {
  b = {
    c: 1
  }
}
d: ${a} {
  b : {
    d: 2
  }
}
```
or 
```
a: {
  b = {
    c: 1
  }
}
d: ${a} {
  b = {
    d: 2
  }
}
```
I would like to parse it to be
```
a: {
  b: {
    c: 1
  }
}
d: {
  b: {
    d: 2
  }
}
```

instead of 

```
a: {
  b: {
    c: 1
  }
}
d: {
  b: {
    c: 1
    d: 2
  }
}
```
Thanks.

**Comment by havocp** [comment]
It wouldn't be backward compatible to change the behavior, but it is possible to prevent merging by including an intermediate value:

```
a = { b : 2 }
a = null
a = { c : 3 }
```
