### ISSUE TITLE
Not possible to use "+" character at the end of key name

### ISSUE THREAD

**Issue by jurek7** [lightbend/config#737]
I have the following configuration:
`rootkey : {
    "1234 - project D+": 1234
}`

When I'm trying to check if rootkey object using hasPath method I'm getting the following error:

`Token not allowed in path expression: 'end of file' ('+' not followed by =, 'end of file' not allowed after '+') (you can double-quote this token if you really want it here)`

It seems that it is not possible to have "+" character at the end of key name. I tried multiple to escape this character in many ways to solve this issue with no success.

**Comment by havocp** [comment]
something like `hasPath("\"+\"")` should work I think. Or use a key method (from ConfigObject) instead of a path method (from Config).

**Comment by jurek7** [comment]
Thanks it works. I think I wrongly assumed that the problem was in the configuration file.
